// <auto-generated />
namespace E_Commerce_With_Rest_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class frkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(frkey));
        
        string IMigrationMetadata.Id
        {
            get { return "202105041030505_frkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
