// <auto-generated />
namespace E_Commerce_With_Rest_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class haetos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(haetos));
        
        string IMigrationMetadata.Id
        {
            get { return "202105050351247_haetos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
